package com.money.debt.bean;

import java.math.BigDecimal;
import java.util.Date;

public class CallRecordIn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.uniqueId
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String uniqueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.customerNumber
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String customernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.customerProvince
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String customerprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.customerCity
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String customercity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.numberTrunk
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String numbertrunk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.queueName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String queuename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.cno
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.clientNumber
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String clientnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.callStatus
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String callstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.startTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.bridgeTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String bridgetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.bridgeDuration
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String bridgeduration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.cost
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.totalDuration
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String totalduration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.recordFile
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String recordfile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.inCaseLib
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String incaselib;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.score
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.callType
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String calltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.taskName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String taskname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.endReason
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String endreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.userField
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String userfield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.sipCause
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String sipcause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.mark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.answerTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date answertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.hotline
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String hotline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.ivrName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String ivrname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_record_in.comment
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.id
     *
     * @return the value of call_record_in.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.id
     *
     * @param id the value for call_record_in.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.uniqueId
     *
     * @return the value of call_record_in.uniqueId
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getUniqueid() {
        return uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.uniqueId
     *
     * @param uniqueid the value for call_record_in.uniqueId
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid == null ? null : uniqueid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.customerNumber
     *
     * @return the value of call_record_in.customerNumber
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCustomernumber() {
        return customernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.customerNumber
     *
     * @param customernumber the value for call_record_in.customerNumber
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCustomernumber(String customernumber) {
        this.customernumber = customernumber == null ? null : customernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.customerProvince
     *
     * @return the value of call_record_in.customerProvince
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCustomerprovince() {
        return customerprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.customerProvince
     *
     * @param customerprovince the value for call_record_in.customerProvince
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCustomerprovince(String customerprovince) {
        this.customerprovince = customerprovince == null ? null : customerprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.customerCity
     *
     * @return the value of call_record_in.customerCity
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCustomercity() {
        return customercity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.customerCity
     *
     * @param customercity the value for call_record_in.customerCity
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCustomercity(String customercity) {
        this.customercity = customercity == null ? null : customercity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.numberTrunk
     *
     * @return the value of call_record_in.numberTrunk
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getNumbertrunk() {
        return numbertrunk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.numberTrunk
     *
     * @param numbertrunk the value for call_record_in.numberTrunk
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setNumbertrunk(String numbertrunk) {
        this.numbertrunk = numbertrunk == null ? null : numbertrunk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.queueName
     *
     * @return the value of call_record_in.queueName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getQueuename() {
        return queuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.queueName
     *
     * @param queuename the value for call_record_in.queueName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setQueuename(String queuename) {
        this.queuename = queuename == null ? null : queuename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.cno
     *
     * @return the value of call_record_in.cno
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.cno
     *
     * @param cno the value for call_record_in.cno
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.clientNumber
     *
     * @return the value of call_record_in.clientNumber
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getClientnumber() {
        return clientnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.clientNumber
     *
     * @param clientnumber the value for call_record_in.clientNumber
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setClientnumber(String clientnumber) {
        this.clientnumber = clientnumber == null ? null : clientnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.callStatus
     *
     * @return the value of call_record_in.callStatus
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCallstatus() {
        return callstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.callStatus
     *
     * @param callstatus the value for call_record_in.callStatus
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCallstatus(String callstatus) {
        this.callstatus = callstatus == null ? null : callstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.startTime
     *
     * @return the value of call_record_in.startTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.startTime
     *
     * @param starttime the value for call_record_in.startTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.bridgeTime
     *
     * @return the value of call_record_in.bridgeTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getBridgetime() {
        return bridgetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.bridgeTime
     *
     * @param bridgetime the value for call_record_in.bridgeTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setBridgetime(String bridgetime) {
        this.bridgetime = bridgetime == null ? null : bridgetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.bridgeDuration
     *
     * @return the value of call_record_in.bridgeDuration
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getBridgeduration() {
        return bridgeduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.bridgeDuration
     *
     * @param bridgeduration the value for call_record_in.bridgeDuration
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setBridgeduration(String bridgeduration) {
        this.bridgeduration = bridgeduration == null ? null : bridgeduration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.cost
     *
     * @return the value of call_record_in.cost
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.cost
     *
     * @param cost the value for call_record_in.cost
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.totalDuration
     *
     * @return the value of call_record_in.totalDuration
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getTotalduration() {
        return totalduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.totalDuration
     *
     * @param totalduration the value for call_record_in.totalDuration
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setTotalduration(String totalduration) {
        this.totalduration = totalduration == null ? null : totalduration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.recordFile
     *
     * @return the value of call_record_in.recordFile
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getRecordfile() {
        return recordfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.recordFile
     *
     * @param recordfile the value for call_record_in.recordFile
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setRecordfile(String recordfile) {
        this.recordfile = recordfile == null ? null : recordfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.inCaseLib
     *
     * @return the value of call_record_in.inCaseLib
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getIncaselib() {
        return incaselib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.inCaseLib
     *
     * @param incaselib the value for call_record_in.inCaseLib
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setIncaselib(String incaselib) {
        this.incaselib = incaselib == null ? null : incaselib.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.score
     *
     * @return the value of call_record_in.score
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.score
     *
     * @param score the value for call_record_in.score
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.callType
     *
     * @return the value of call_record_in.callType
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCalltype() {
        return calltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.callType
     *
     * @param calltype the value for call_record_in.callType
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCalltype(String calltype) {
        this.calltype = calltype == null ? null : calltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.taskName
     *
     * @return the value of call_record_in.taskName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.taskName
     *
     * @param taskname the value for call_record_in.taskName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname == null ? null : taskname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.endReason
     *
     * @return the value of call_record_in.endReason
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEndreason() {
        return endreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.endReason
     *
     * @param endreason the value for call_record_in.endReason
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEndreason(String endreason) {
        this.endreason = endreason == null ? null : endreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.userField
     *
     * @return the value of call_record_in.userField
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getUserfield() {
        return userfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.userField
     *
     * @param userfield the value for call_record_in.userField
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setUserfield(String userfield) {
        this.userfield = userfield == null ? null : userfield.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.sipCause
     *
     * @return the value of call_record_in.sipCause
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSipcause() {
        return sipcause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.sipCause
     *
     * @param sipcause the value for call_record_in.sipCause
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSipcause(String sipcause) {
        this.sipcause = sipcause == null ? null : sipcause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.mark
     *
     * @return the value of call_record_in.mark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.mark
     *
     * @param mark the value for call_record_in.mark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.answerTime
     *
     * @return the value of call_record_in.answerTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getAnswertime() {
        return answertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.answerTime
     *
     * @param answertime the value for call_record_in.answerTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setAnswertime(Date answertime) {
        this.answertime = answertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.hotline
     *
     * @return the value of call_record_in.hotline
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getHotline() {
        return hotline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.hotline
     *
     * @param hotline the value for call_record_in.hotline
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setHotline(String hotline) {
        this.hotline = hotline == null ? null : hotline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.ivrName
     *
     * @return the value of call_record_in.ivrName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getIvrname() {
        return ivrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.ivrName
     *
     * @param ivrname the value for call_record_in.ivrName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setIvrname(String ivrname) {
        this.ivrname = ivrname == null ? null : ivrname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_record_in.comment
     *
     * @return the value of call_record_in.comment
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_record_in.comment
     *
     * @param comment the value for call_record_in.comment
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}