package com.money.debt.bean;

import java.util.Date;

public class CnoInStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.cno
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.org_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.callInCount
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer callincount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.callInConnectCount
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer callinconnectcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.callInConnectDuration
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String callinconnectduration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.callInConnectDurationAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String callinconnectdurationavg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.callInConnectRate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String callinconnectrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.bridgeDurationDayAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String bridgedurationdayavg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cno_in_statistics.createTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.id
     *
     * @return the value of cno_in_statistics.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.id
     *
     * @param id the value for cno_in_statistics.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.cno
     *
     * @return the value of cno_in_statistics.cno
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.cno
     *
     * @param cno the value for cno_in_statistics.cno
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.emp_id
     *
     * @return the value of cno_in_statistics.emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.emp_id
     *
     * @param empId the value for cno_in_statistics.emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.emp_name
     *
     * @return the value of cno_in_statistics.emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.emp_name
     *
     * @param empName the value for cno_in_statistics.emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.org_id
     *
     * @return the value of cno_in_statistics.org_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.org_id
     *
     * @param orgId the value for cno_in_statistics.org_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.callInCount
     *
     * @return the value of cno_in_statistics.callInCount
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getCallincount() {
        return callincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.callInCount
     *
     * @param callincount the value for cno_in_statistics.callInCount
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCallincount(Integer callincount) {
        this.callincount = callincount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.callInConnectCount
     *
     * @return the value of cno_in_statistics.callInConnectCount
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getCallinconnectcount() {
        return callinconnectcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.callInConnectCount
     *
     * @param callinconnectcount the value for cno_in_statistics.callInConnectCount
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCallinconnectcount(Integer callinconnectcount) {
        this.callinconnectcount = callinconnectcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.callInConnectDuration
     *
     * @return the value of cno_in_statistics.callInConnectDuration
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCallinconnectduration() {
        return callinconnectduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.callInConnectDuration
     *
     * @param callinconnectduration the value for cno_in_statistics.callInConnectDuration
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCallinconnectduration(String callinconnectduration) {
        this.callinconnectduration = callinconnectduration == null ? null : callinconnectduration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.callInConnectDurationAvg
     *
     * @return the value of cno_in_statistics.callInConnectDurationAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCallinconnectdurationavg() {
        return callinconnectdurationavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.callInConnectDurationAvg
     *
     * @param callinconnectdurationavg the value for cno_in_statistics.callInConnectDurationAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCallinconnectdurationavg(String callinconnectdurationavg) {
        this.callinconnectdurationavg = callinconnectdurationavg == null ? null : callinconnectdurationavg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.callInConnectRate
     *
     * @return the value of cno_in_statistics.callInConnectRate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCallinconnectrate() {
        return callinconnectrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.callInConnectRate
     *
     * @param callinconnectrate the value for cno_in_statistics.callInConnectRate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCallinconnectrate(String callinconnectrate) {
        this.callinconnectrate = callinconnectrate == null ? null : callinconnectrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.bridgeDurationDayAvg
     *
     * @return the value of cno_in_statistics.bridgeDurationDayAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getBridgedurationdayavg() {
        return bridgedurationdayavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.bridgeDurationDayAvg
     *
     * @param bridgedurationdayavg the value for cno_in_statistics.bridgeDurationDayAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setBridgedurationdayavg(String bridgedurationdayavg) {
        this.bridgedurationdayavg = bridgedurationdayavg == null ? null : bridgedurationdayavg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cno_in_statistics.createTime
     *
     * @return the value of cno_in_statistics.createTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cno_in_statistics.createTime
     *
     * @param createtime the value for cno_in_statistics.createTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}