package com.money.debt.bean;

import java.math.BigDecimal;
import java.util.Date;

public class EntrustProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.staff_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.case_source_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String caseSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.case_type_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String caseTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.case_type_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String caseTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.handle
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String handle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.handle_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String handleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.cus_type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String cusType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.rate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private BigDecimal rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.entrust_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String entrustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.entrust_abbrevia
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String entrustAbbrevia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.product_category_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String productCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.guarantee_way_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String guaranteeWayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.purpose_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String purposeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.contract_award_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date contractAwardDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.contract_cycle
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String contractCycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.custom_service_total
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String customServiceTotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.service_project
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String serviceProject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.area_id1
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String areaId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.area_id2
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String areaId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.area_id3
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String areaId3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.staff
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String staff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.create_emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String createEmpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_product.modify_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String modifyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.id
     *
     * @return the value of entrust_product.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.id
     *
     * @param id the value for entrust_product.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.staff_name
     *
     * @return the value of entrust_product.staff_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.staff_name
     *
     * @param staffName the value for entrust_product.staff_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.case_source_id
     *
     * @return the value of entrust_product.case_source_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCaseSourceId() {
        return caseSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.case_source_id
     *
     * @param caseSourceId the value for entrust_product.case_source_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCaseSourceId(String caseSourceId) {
        this.caseSourceId = caseSourceId == null ? null : caseSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.case_type_id
     *
     * @return the value of entrust_product.case_type_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCaseTypeId() {
        return caseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.case_type_id
     *
     * @param caseTypeId the value for entrust_product.case_type_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCaseTypeId(String caseTypeId) {
        this.caseTypeId = caseTypeId == null ? null : caseTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.case_type_name
     *
     * @return the value of entrust_product.case_type_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCaseTypeName() {
        return caseTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.case_type_name
     *
     * @param caseTypeName the value for entrust_product.case_type_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCaseTypeName(String caseTypeName) {
        this.caseTypeName = caseTypeName == null ? null : caseTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.handle
     *
     * @return the value of entrust_product.handle
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getHandle() {
        return handle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.handle
     *
     * @param handle the value for entrust_product.handle
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setHandle(String handle) {
        this.handle = handle == null ? null : handle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.handle_name
     *
     * @return the value of entrust_product.handle_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getHandleName() {
        return handleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.handle_name
     *
     * @param handleName the value for entrust_product.handle_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setHandleName(String handleName) {
        this.handleName = handleName == null ? null : handleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.code
     *
     * @return the value of entrust_product.code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.code
     *
     * @param code the value for entrust_product.code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.cus_type
     *
     * @return the value of entrust_product.cus_type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCusType() {
        return cusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.cus_type
     *
     * @param cusType the value for entrust_product.cus_type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCusType(String cusType) {
        this.cusType = cusType == null ? null : cusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.rate
     *
     * @return the value of entrust_product.rate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.rate
     *
     * @param rate the value for entrust_product.rate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.entrust_id
     *
     * @return the value of entrust_product.entrust_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEntrustId() {
        return entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.entrust_id
     *
     * @param entrustId the value for entrust_product.entrust_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEntrustId(String entrustId) {
        this.entrustId = entrustId == null ? null : entrustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.entrust_abbrevia
     *
     * @return the value of entrust_product.entrust_abbrevia
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEntrustAbbrevia() {
        return entrustAbbrevia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.entrust_abbrevia
     *
     * @param entrustAbbrevia the value for entrust_product.entrust_abbrevia
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEntrustAbbrevia(String entrustAbbrevia) {
        this.entrustAbbrevia = entrustAbbrevia == null ? null : entrustAbbrevia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.product_category_id
     *
     * @return the value of entrust_product.product_category_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getProductCategoryId() {
        return productCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.product_category_id
     *
     * @param productCategoryId the value for entrust_product.product_category_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setProductCategoryId(String productCategoryId) {
        this.productCategoryId = productCategoryId == null ? null : productCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.guarantee_way_id
     *
     * @return the value of entrust_product.guarantee_way_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getGuaranteeWayId() {
        return guaranteeWayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.guarantee_way_id
     *
     * @param guaranteeWayId the value for entrust_product.guarantee_way_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setGuaranteeWayId(String guaranteeWayId) {
        this.guaranteeWayId = guaranteeWayId == null ? null : guaranteeWayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.purpose_id
     *
     * @return the value of entrust_product.purpose_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getPurposeId() {
        return purposeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.purpose_id
     *
     * @param purposeId the value for entrust_product.purpose_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setPurposeId(String purposeId) {
        this.purposeId = purposeId == null ? null : purposeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.contract_award_date
     *
     * @return the value of entrust_product.contract_award_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getContractAwardDate() {
        return contractAwardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.contract_award_date
     *
     * @param contractAwardDate the value for entrust_product.contract_award_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setContractAwardDate(Date contractAwardDate) {
        this.contractAwardDate = contractAwardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.contract_cycle
     *
     * @return the value of entrust_product.contract_cycle
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getContractCycle() {
        return contractCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.contract_cycle
     *
     * @param contractCycle the value for entrust_product.contract_cycle
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setContractCycle(String contractCycle) {
        this.contractCycle = contractCycle == null ? null : contractCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.custom_service_total
     *
     * @return the value of entrust_product.custom_service_total
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCustomServiceTotal() {
        return customServiceTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.custom_service_total
     *
     * @param customServiceTotal the value for entrust_product.custom_service_total
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCustomServiceTotal(String customServiceTotal) {
        this.customServiceTotal = customServiceTotal == null ? null : customServiceTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.service_project
     *
     * @return the value of entrust_product.service_project
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getServiceProject() {
        return serviceProject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.service_project
     *
     * @param serviceProject the value for entrust_product.service_project
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setServiceProject(String serviceProject) {
        this.serviceProject = serviceProject == null ? null : serviceProject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.area_id1
     *
     * @return the value of entrust_product.area_id1
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getAreaId1() {
        return areaId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.area_id1
     *
     * @param areaId1 the value for entrust_product.area_id1
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setAreaId1(String areaId1) {
        this.areaId1 = areaId1 == null ? null : areaId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.area_id2
     *
     * @return the value of entrust_product.area_id2
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getAreaId2() {
        return areaId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.area_id2
     *
     * @param areaId2 the value for entrust_product.area_id2
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setAreaId2(String areaId2) {
        this.areaId2 = areaId2 == null ? null : areaId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.area_id3
     *
     * @return the value of entrust_product.area_id3
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getAreaId3() {
        return areaId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.area_id3
     *
     * @param areaId3 the value for entrust_product.area_id3
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setAreaId3(String areaId3) {
        this.areaId3 = areaId3 == null ? null : areaId3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.address
     *
     * @return the value of entrust_product.address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.address
     *
     * @param address the value for entrust_product.address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.staff
     *
     * @return the value of entrust_product.staff
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getStaff() {
        return staff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.staff
     *
     * @param staff the value for entrust_product.staff
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setStaff(String staff) {
        this.staff = staff == null ? null : staff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.create_emp_id
     *
     * @return the value of entrust_product.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.create_emp_id
     *
     * @param createEmpId the value for entrust_product.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.create_emp_name
     *
     * @return the value of entrust_product.create_emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCreateEmpName() {
        return createEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.create_emp_name
     *
     * @param createEmpName the value for entrust_product.create_emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateEmpName(String createEmpName) {
        this.createEmpName = createEmpName == null ? null : createEmpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.create_time
     *
     * @return the value of entrust_product.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.create_time
     *
     * @param createTime the value for entrust_product.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.state
     *
     * @return the value of entrust_product.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.state
     *
     * @param state the value for entrust_product.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.modify_time
     *
     * @return the value of entrust_product.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.modify_time
     *
     * @param modifyTime the value for entrust_product.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_product.modify_name
     *
     * @return the value of entrust_product.modify_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getModifyName() {
        return modifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_product.modify_name
     *
     * @param modifyName the value for entrust_product.modify_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setModifyName(String modifyName) {
        this.modifyName = modifyName == null ? null : modifyName.trim();
    }
}