package com.money.debt.bean;

import java.util.Date;

public class EntrustLinkman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.entrust_product_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String entrustProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.qq
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.WeChat
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.position
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.create_emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String createEmpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.modify_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String modifyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_linkman.remark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.id
     *
     * @return the value of entrust_linkman.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.id
     *
     * @param id the value for entrust_linkman.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.entrust_product_id
     *
     * @return the value of entrust_linkman.entrust_product_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEntrustProductId() {
        return entrustProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.entrust_product_id
     *
     * @param entrustProductId the value for entrust_linkman.entrust_product_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEntrustProductId(String entrustProductId) {
        this.entrustProductId = entrustProductId == null ? null : entrustProductId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.name
     *
     * @return the value of entrust_linkman.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.name
     *
     * @param name the value for entrust_linkman.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.qq
     *
     * @return the value of entrust_linkman.qq
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.qq
     *
     * @param qq the value for entrust_linkman.qq
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.WeChat
     *
     * @return the value of entrust_linkman.WeChat
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.WeChat
     *
     * @param wechat the value for entrust_linkman.WeChat
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.phone
     *
     * @return the value of entrust_linkman.phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.phone
     *
     * @param phone the value for entrust_linkman.phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.position
     *
     * @return the value of entrust_linkman.position
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.position
     *
     * @param position the value for entrust_linkman.position
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.email
     *
     * @return the value of entrust_linkman.email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.email
     *
     * @param email the value for entrust_linkman.email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.create_time
     *
     * @return the value of entrust_linkman.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.create_time
     *
     * @param createTime the value for entrust_linkman.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.create_emp_id
     *
     * @return the value of entrust_linkman.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.create_emp_id
     *
     * @param createEmpId the value for entrust_linkman.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.create_emp_name
     *
     * @return the value of entrust_linkman.create_emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCreateEmpName() {
        return createEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.create_emp_name
     *
     * @param createEmpName the value for entrust_linkman.create_emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateEmpName(String createEmpName) {
        this.createEmpName = createEmpName == null ? null : createEmpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.modify_time
     *
     * @return the value of entrust_linkman.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.modify_time
     *
     * @param modifyTime the value for entrust_linkman.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.modify_name
     *
     * @return the value of entrust_linkman.modify_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getModifyName() {
        return modifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.modify_name
     *
     * @param modifyName the value for entrust_linkman.modify_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setModifyName(String modifyName) {
        this.modifyName = modifyName == null ? null : modifyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_linkman.remark
     *
     * @return the value of entrust_linkman.remark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_linkman.remark
     *
     * @param remark the value for entrust_linkman.remark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}