package com.money.debt.bean;

public class EntrustCaseProductReleation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.entrust_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String entrustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.entrust_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String entrustName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.product_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.case_source_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String caseSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.case_source_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String caseSourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.case_type_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String caseTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.case_type_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String caseTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.handle_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String handleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column entrust_case_product_releation.handle_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String handleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.id
     *
     * @return the value of entrust_case_product_releation.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.id
     *
     * @param id the value for entrust_case_product_releation.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.entrust_id
     *
     * @return the value of entrust_case_product_releation.entrust_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEntrustId() {
        return entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.entrust_id
     *
     * @param entrustId the value for entrust_case_product_releation.entrust_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEntrustId(String entrustId) {
        this.entrustId = entrustId == null ? null : entrustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.entrust_name
     *
     * @return the value of entrust_case_product_releation.entrust_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEntrustName() {
        return entrustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.entrust_name
     *
     * @param entrustName the value for entrust_case_product_releation.entrust_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEntrustName(String entrustName) {
        this.entrustName = entrustName == null ? null : entrustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.product_id
     *
     * @return the value of entrust_case_product_releation.product_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.product_id
     *
     * @param productId the value for entrust_case_product_releation.product_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.case_source_id
     *
     * @return the value of entrust_case_product_releation.case_source_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCaseSourceId() {
        return caseSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.case_source_id
     *
     * @param caseSourceId the value for entrust_case_product_releation.case_source_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCaseSourceId(String caseSourceId) {
        this.caseSourceId = caseSourceId == null ? null : caseSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.case_source_name
     *
     * @return the value of entrust_case_product_releation.case_source_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCaseSourceName() {
        return caseSourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.case_source_name
     *
     * @param caseSourceName the value for entrust_case_product_releation.case_source_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCaseSourceName(String caseSourceName) {
        this.caseSourceName = caseSourceName == null ? null : caseSourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.case_type_id
     *
     * @return the value of entrust_case_product_releation.case_type_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCaseTypeId() {
        return caseTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.case_type_id
     *
     * @param caseTypeId the value for entrust_case_product_releation.case_type_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCaseTypeId(String caseTypeId) {
        this.caseTypeId = caseTypeId == null ? null : caseTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.case_type_name
     *
     * @return the value of entrust_case_product_releation.case_type_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCaseTypeName() {
        return caseTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.case_type_name
     *
     * @param caseTypeName the value for entrust_case_product_releation.case_type_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCaseTypeName(String caseTypeName) {
        this.caseTypeName = caseTypeName == null ? null : caseTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.code
     *
     * @return the value of entrust_case_product_releation.code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.code
     *
     * @param code the value for entrust_case_product_releation.code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.handle_id
     *
     * @return the value of entrust_case_product_releation.handle_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getHandleId() {
        return handleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.handle_id
     *
     * @param handleId the value for entrust_case_product_releation.handle_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setHandleId(String handleId) {
        this.handleId = handleId == null ? null : handleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column entrust_case_product_releation.handle_name
     *
     * @return the value of entrust_case_product_releation.handle_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getHandleName() {
        return handleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column entrust_case_product_releation.handle_name
     *
     * @param handleName the value for entrust_case_product_releation.handle_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setHandleName(String handleName) {
        this.handleName = handleName == null ? null : handleName.trim();
    }
}