package com.money.debt.bean;

import java.util.Date;

public class Express {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.case_apply_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String caseApplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.card_type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.card_num
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.his_user_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String hisUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.mobile
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.family_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String familyPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.family_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String familyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.qq
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.qq_group
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String qqGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.wechat
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.blog
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String blog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.consignee_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String consigneeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.consignee_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String consigneePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.consignee_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String consigneeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.unit_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.unit_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String unitPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.unit_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String unitAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.important_linkman_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String importantLinkmanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.important_linkman_cardNum
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String importantLinkmanCardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.important_linkman_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String importantLinkmanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.important_linkman_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String importantLinkmanAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.linkman_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String linkmanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.linkman_cardNum
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String linkmanCardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.linkman_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String linkmanPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.linkman_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String linkmanAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.linkman_unitName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String linkmanUnitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.obtain_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date obtainTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.status
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.remark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.id
     *
     * @return the value of express.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.id
     *
     * @param id the value for express.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.case_apply_id
     *
     * @return the value of express.case_apply_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCaseApplyId() {
        return caseApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.case_apply_id
     *
     * @param caseApplyId the value for express.case_apply_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCaseApplyId(String caseApplyId) {
        this.caseApplyId = caseApplyId == null ? null : caseApplyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.name
     *
     * @return the value of express.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.name
     *
     * @param name the value for express.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.card_type
     *
     * @return the value of express.card_type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.card_type
     *
     * @param cardType the value for express.card_type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.card_num
     *
     * @return the value of express.card_num
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.card_num
     *
     * @param cardNum the value for express.card_num
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum == null ? null : cardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.his_user_name
     *
     * @return the value of express.his_user_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getHisUserName() {
        return hisUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.his_user_name
     *
     * @param hisUserName the value for express.his_user_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setHisUserName(String hisUserName) {
        this.hisUserName = hisUserName == null ? null : hisUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.mobile
     *
     * @return the value of express.mobile
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.mobile
     *
     * @param mobile the value for express.mobile
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.family_phone
     *
     * @return the value of express.family_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getFamilyPhone() {
        return familyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.family_phone
     *
     * @param familyPhone the value for express.family_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setFamilyPhone(String familyPhone) {
        this.familyPhone = familyPhone == null ? null : familyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.family_address
     *
     * @return the value of express.family_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getFamilyAddress() {
        return familyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.family_address
     *
     * @param familyAddress the value for express.family_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setFamilyAddress(String familyAddress) {
        this.familyAddress = familyAddress == null ? null : familyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.email
     *
     * @return the value of express.email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.email
     *
     * @param email the value for express.email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.qq
     *
     * @return the value of express.qq
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.qq
     *
     * @param qq the value for express.qq
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.qq_group
     *
     * @return the value of express.qq_group
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getQqGroup() {
        return qqGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.qq_group
     *
     * @param qqGroup the value for express.qq_group
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setQqGroup(String qqGroup) {
        this.qqGroup = qqGroup == null ? null : qqGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.wechat
     *
     * @return the value of express.wechat
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.wechat
     *
     * @param wechat the value for express.wechat
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.blog
     *
     * @return the value of express.blog
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getBlog() {
        return blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.blog
     *
     * @param blog the value for express.blog
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setBlog(String blog) {
        this.blog = blog == null ? null : blog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.consignee_name
     *
     * @return the value of express.consignee_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getConsigneeName() {
        return consigneeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.consignee_name
     *
     * @param consigneeName the value for express.consignee_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setConsigneeName(String consigneeName) {
        this.consigneeName = consigneeName == null ? null : consigneeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.consignee_phone
     *
     * @return the value of express.consignee_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getConsigneePhone() {
        return consigneePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.consignee_phone
     *
     * @param consigneePhone the value for express.consignee_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone == null ? null : consigneePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.consignee_address
     *
     * @return the value of express.consignee_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getConsigneeAddress() {
        return consigneeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.consignee_address
     *
     * @param consigneeAddress the value for express.consignee_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setConsigneeAddress(String consigneeAddress) {
        this.consigneeAddress = consigneeAddress == null ? null : consigneeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.unit_name
     *
     * @return the value of express.unit_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.unit_name
     *
     * @param unitName the value for express.unit_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.unit_phone
     *
     * @return the value of express.unit_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getUnitPhone() {
        return unitPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.unit_phone
     *
     * @param unitPhone the value for express.unit_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setUnitPhone(String unitPhone) {
        this.unitPhone = unitPhone == null ? null : unitPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.unit_address
     *
     * @return the value of express.unit_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getUnitAddress() {
        return unitAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.unit_address
     *
     * @param unitAddress the value for express.unit_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setUnitAddress(String unitAddress) {
        this.unitAddress = unitAddress == null ? null : unitAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.important_linkman_name
     *
     * @return the value of express.important_linkman_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getImportantLinkmanName() {
        return importantLinkmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.important_linkman_name
     *
     * @param importantLinkmanName the value for express.important_linkman_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setImportantLinkmanName(String importantLinkmanName) {
        this.importantLinkmanName = importantLinkmanName == null ? null : importantLinkmanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.important_linkman_cardNum
     *
     * @return the value of express.important_linkman_cardNum
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getImportantLinkmanCardnum() {
        return importantLinkmanCardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.important_linkman_cardNum
     *
     * @param importantLinkmanCardnum the value for express.important_linkman_cardNum
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setImportantLinkmanCardnum(String importantLinkmanCardnum) {
        this.importantLinkmanCardnum = importantLinkmanCardnum == null ? null : importantLinkmanCardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.important_linkman_phone
     *
     * @return the value of express.important_linkman_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getImportantLinkmanPhone() {
        return importantLinkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.important_linkman_phone
     *
     * @param importantLinkmanPhone the value for express.important_linkman_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setImportantLinkmanPhone(String importantLinkmanPhone) {
        this.importantLinkmanPhone = importantLinkmanPhone == null ? null : importantLinkmanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.important_linkman_address
     *
     * @return the value of express.important_linkman_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getImportantLinkmanAddress() {
        return importantLinkmanAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.important_linkman_address
     *
     * @param importantLinkmanAddress the value for express.important_linkman_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setImportantLinkmanAddress(String importantLinkmanAddress) {
        this.importantLinkmanAddress = importantLinkmanAddress == null ? null : importantLinkmanAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.linkman_name
     *
     * @return the value of express.linkman_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getLinkmanName() {
        return linkmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.linkman_name
     *
     * @param linkmanName the value for express.linkman_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setLinkmanName(String linkmanName) {
        this.linkmanName = linkmanName == null ? null : linkmanName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.linkman_cardNum
     *
     * @return the value of express.linkman_cardNum
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getLinkmanCardnum() {
        return linkmanCardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.linkman_cardNum
     *
     * @param linkmanCardnum the value for express.linkman_cardNum
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setLinkmanCardnum(String linkmanCardnum) {
        this.linkmanCardnum = linkmanCardnum == null ? null : linkmanCardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.linkman_phone
     *
     * @return the value of express.linkman_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getLinkmanPhone() {
        return linkmanPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.linkman_phone
     *
     * @param linkmanPhone the value for express.linkman_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setLinkmanPhone(String linkmanPhone) {
        this.linkmanPhone = linkmanPhone == null ? null : linkmanPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.linkman_address
     *
     * @return the value of express.linkman_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getLinkmanAddress() {
        return linkmanAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.linkman_address
     *
     * @param linkmanAddress the value for express.linkman_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setLinkmanAddress(String linkmanAddress) {
        this.linkmanAddress = linkmanAddress == null ? null : linkmanAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.linkman_unitName
     *
     * @return the value of express.linkman_unitName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getLinkmanUnitname() {
        return linkmanUnitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.linkman_unitName
     *
     * @param linkmanUnitname the value for express.linkman_unitName
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setLinkmanUnitname(String linkmanUnitname) {
        this.linkmanUnitname = linkmanUnitname == null ? null : linkmanUnitname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.obtain_time
     *
     * @return the value of express.obtain_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getObtainTime() {
        return obtainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.obtain_time
     *
     * @param obtainTime the value for express.obtain_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setObtainTime(Date obtainTime) {
        this.obtainTime = obtainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.create_time
     *
     * @return the value of express.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.create_time
     *
     * @param createTime the value for express.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.create_emp_id
     *
     * @return the value of express.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.create_emp_id
     *
     * @param createEmpId the value for express.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.status
     *
     * @return the value of express.status
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.status
     *
     * @param status the value for express.status
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.remark
     *
     * @return the value of express.remark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.remark
     *
     * @param remark the value for express.remark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}