package com.money.debt.bean;

public class Holiday {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column holiday.holiday
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String holiday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.id
     *
     * @return the value of holiday.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.id
     *
     * @param id the value for holiday.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday.holiday
     *
     * @return the value of holiday.holiday
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getHoliday() {
        return holiday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday.holiday
     *
     * @param holiday the value for holiday.holiday
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setHoliday(String holiday) {
        this.holiday = holiday == null ? null : holiday.trim();
    }
}