package com.money.debt.bean;

import java.util.Date;

public class LastPhoneTime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column last_phone_time.case_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column last_phone_time.time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column last_phone_time.case_id
     *
     * @return the value of last_phone_time.case_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column last_phone_time.case_id
     *
     * @param caseId the value for last_phone_time.case_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId == null ? null : caseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column last_phone_time.time
     *
     * @return the value of last_phone_time.time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column last_phone_time.time
     *
     * @param time the value for last_phone_time.time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}