package com.money.debt.bean;

import java.util.Date;

public class SalEmp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_no
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Long seNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_so_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seSoCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_ide_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seIdeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_pos
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String sePos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_sex
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_prob
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seProb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_bir_place
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seBirPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_acc_place
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seAccPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_birth
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_marry
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seMarry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_job_lev
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Long seJobLev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_job_cate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seJobCate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_job_title
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seJobTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_start_day
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date seStartDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_year_pay
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seYearPay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_cost_center
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seCostCenter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_nation
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_poli_status
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String sePoliStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_edu
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seEdu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_tel
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String sePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_qq
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_msn
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seMsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_rec_source
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seRecSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_prov_fund
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seProvFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_job_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date seJobDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_hou_reg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seHouReg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_social_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seSocialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_rap
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seRap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_bank_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_bank_card
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seBankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_weal_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seWealAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_weal_pos
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seWealPos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_isovertime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seIsovertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_attendance
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seAttendance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_card_num
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seCardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_isenabled
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seIsenabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_inser_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date seInserDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_alt_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date seAltDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_inser_user
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seInserUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_alt_user
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seAltUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_end_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date seEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_user_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_per_tel
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String sePerTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_plan_sign_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date sePlanSignDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_sign_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date seSignDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_credit_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date seCreditDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_college
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seCollege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_remark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_pic
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String sePic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_log
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_edc_bac
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seEdcBac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_work_ex
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seWorkEx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_emp.se_transfer
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String seTransfer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_no
     *
     * @return the value of sal_emp.se_no
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Long getSeNo() {
        return seNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_no
     *
     * @param seNo the value for sal_emp.se_no
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeNo(Long seNo) {
        this.seNo = seNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_so_code
     *
     * @return the value of sal_emp.se_so_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeSoCode() {
        return seSoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_so_code
     *
     * @param seSoCode the value for sal_emp.se_so_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeSoCode(String seSoCode) {
        this.seSoCode = seSoCode == null ? null : seSoCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_name
     *
     * @return the value of sal_emp.se_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeName() {
        return seName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_name
     *
     * @param seName the value for sal_emp.se_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeName(String seName) {
        this.seName = seName == null ? null : seName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_ide_code
     *
     * @return the value of sal_emp.se_ide_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeIdeCode() {
        return seIdeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_ide_code
     *
     * @param seIdeCode the value for sal_emp.se_ide_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeIdeCode(String seIdeCode) {
        this.seIdeCode = seIdeCode == null ? null : seIdeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_pos
     *
     * @return the value of sal_emp.se_pos
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSePos() {
        return sePos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_pos
     *
     * @param sePos the value for sal_emp.se_pos
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSePos(String sePos) {
        this.sePos = sePos == null ? null : sePos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_sex
     *
     * @return the value of sal_emp.se_sex
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeSex() {
        return seSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_sex
     *
     * @param seSex the value for sal_emp.se_sex
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeSex(String seSex) {
        this.seSex = seSex == null ? null : seSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_prob
     *
     * @return the value of sal_emp.se_prob
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeProb() {
        return seProb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_prob
     *
     * @param seProb the value for sal_emp.se_prob
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeProb(String seProb) {
        this.seProb = seProb == null ? null : seProb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_bir_place
     *
     * @return the value of sal_emp.se_bir_place
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeBirPlace() {
        return seBirPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_bir_place
     *
     * @param seBirPlace the value for sal_emp.se_bir_place
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeBirPlace(String seBirPlace) {
        this.seBirPlace = seBirPlace == null ? null : seBirPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_acc_place
     *
     * @return the value of sal_emp.se_acc_place
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeAccPlace() {
        return seAccPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_acc_place
     *
     * @param seAccPlace the value for sal_emp.se_acc_place
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeAccPlace(String seAccPlace) {
        this.seAccPlace = seAccPlace == null ? null : seAccPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_birth
     *
     * @return the value of sal_emp.se_birth
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeBirth() {
        return seBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_birth
     *
     * @param seBirth the value for sal_emp.se_birth
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeBirth(String seBirth) {
        this.seBirth = seBirth == null ? null : seBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_marry
     *
     * @return the value of sal_emp.se_marry
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeMarry() {
        return seMarry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_marry
     *
     * @param seMarry the value for sal_emp.se_marry
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeMarry(String seMarry) {
        this.seMarry = seMarry == null ? null : seMarry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_type
     *
     * @return the value of sal_emp.se_type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeType() {
        return seType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_type
     *
     * @param seType the value for sal_emp.se_type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeType(String seType) {
        this.seType = seType == null ? null : seType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_job_lev
     *
     * @return the value of sal_emp.se_job_lev
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Long getSeJobLev() {
        return seJobLev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_job_lev
     *
     * @param seJobLev the value for sal_emp.se_job_lev
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeJobLev(Long seJobLev) {
        this.seJobLev = seJobLev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_job_cate
     *
     * @return the value of sal_emp.se_job_cate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeJobCate() {
        return seJobCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_job_cate
     *
     * @param seJobCate the value for sal_emp.se_job_cate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeJobCate(String seJobCate) {
        this.seJobCate = seJobCate == null ? null : seJobCate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_job_title
     *
     * @return the value of sal_emp.se_job_title
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeJobTitle() {
        return seJobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_job_title
     *
     * @param seJobTitle the value for sal_emp.se_job_title
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeJobTitle(String seJobTitle) {
        this.seJobTitle = seJobTitle == null ? null : seJobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_start_day
     *
     * @return the value of sal_emp.se_start_day
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getSeStartDay() {
        return seStartDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_start_day
     *
     * @param seStartDay the value for sal_emp.se_start_day
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeStartDay(Date seStartDay) {
        this.seStartDay = seStartDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_year_pay
     *
     * @return the value of sal_emp.se_year_pay
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeYearPay() {
        return seYearPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_year_pay
     *
     * @param seYearPay the value for sal_emp.se_year_pay
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeYearPay(String seYearPay) {
        this.seYearPay = seYearPay == null ? null : seYearPay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_cost_center
     *
     * @return the value of sal_emp.se_cost_center
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeCostCenter() {
        return seCostCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_cost_center
     *
     * @param seCostCenter the value for sal_emp.se_cost_center
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeCostCenter(String seCostCenter) {
        this.seCostCenter = seCostCenter == null ? null : seCostCenter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_email
     *
     * @return the value of sal_emp.se_email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeEmail() {
        return seEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_email
     *
     * @param seEmail the value for sal_emp.se_email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeEmail(String seEmail) {
        this.seEmail = seEmail == null ? null : seEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_nation
     *
     * @return the value of sal_emp.se_nation
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeNation() {
        return seNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_nation
     *
     * @param seNation the value for sal_emp.se_nation
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeNation(String seNation) {
        this.seNation = seNation == null ? null : seNation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_poli_status
     *
     * @return the value of sal_emp.se_poli_status
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSePoliStatus() {
        return sePoliStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_poli_status
     *
     * @param sePoliStatus the value for sal_emp.se_poli_status
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSePoliStatus(String sePoliStatus) {
        this.sePoliStatus = sePoliStatus == null ? null : sePoliStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_edu
     *
     * @return the value of sal_emp.se_edu
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeEdu() {
        return seEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_edu
     *
     * @param seEdu the value for sal_emp.se_edu
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeEdu(String seEdu) {
        this.seEdu = seEdu == null ? null : seEdu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_tel
     *
     * @return the value of sal_emp.se_tel
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeTel() {
        return seTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_tel
     *
     * @param seTel the value for sal_emp.se_tel
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeTel(String seTel) {
        this.seTel = seTel == null ? null : seTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_phone
     *
     * @return the value of sal_emp.se_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSePhone() {
        return sePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_phone
     *
     * @param sePhone the value for sal_emp.se_phone
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSePhone(String sePhone) {
        this.sePhone = sePhone == null ? null : sePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_qq
     *
     * @return the value of sal_emp.se_qq
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeQq() {
        return seQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_qq
     *
     * @param seQq the value for sal_emp.se_qq
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeQq(String seQq) {
        this.seQq = seQq == null ? null : seQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_msn
     *
     * @return the value of sal_emp.se_msn
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeMsn() {
        return seMsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_msn
     *
     * @param seMsn the value for sal_emp.se_msn
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeMsn(String seMsn) {
        this.seMsn = seMsn == null ? null : seMsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_rec_source
     *
     * @return the value of sal_emp.se_rec_source
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeRecSource() {
        return seRecSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_rec_source
     *
     * @param seRecSource the value for sal_emp.se_rec_source
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeRecSource(String seRecSource) {
        this.seRecSource = seRecSource == null ? null : seRecSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_prov_fund
     *
     * @return the value of sal_emp.se_prov_fund
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeProvFund() {
        return seProvFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_prov_fund
     *
     * @param seProvFund the value for sal_emp.se_prov_fund
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeProvFund(String seProvFund) {
        this.seProvFund = seProvFund == null ? null : seProvFund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_job_date
     *
     * @return the value of sal_emp.se_job_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getSeJobDate() {
        return seJobDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_job_date
     *
     * @param seJobDate the value for sal_emp.se_job_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeJobDate(Date seJobDate) {
        this.seJobDate = seJobDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_hou_reg
     *
     * @return the value of sal_emp.se_hou_reg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeHouReg() {
        return seHouReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_hou_reg
     *
     * @param seHouReg the value for sal_emp.se_hou_reg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeHouReg(String seHouReg) {
        this.seHouReg = seHouReg == null ? null : seHouReg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_social_code
     *
     * @return the value of sal_emp.se_social_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeSocialCode() {
        return seSocialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_social_code
     *
     * @param seSocialCode the value for sal_emp.se_social_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeSocialCode(String seSocialCode) {
        this.seSocialCode = seSocialCode == null ? null : seSocialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_rap
     *
     * @return the value of sal_emp.se_rap
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeRap() {
        return seRap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_rap
     *
     * @param seRap the value for sal_emp.se_rap
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeRap(String seRap) {
        this.seRap = seRap == null ? null : seRap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_bank_name
     *
     * @return the value of sal_emp.se_bank_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeBankName() {
        return seBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_bank_name
     *
     * @param seBankName the value for sal_emp.se_bank_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeBankName(String seBankName) {
        this.seBankName = seBankName == null ? null : seBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_bank_card
     *
     * @return the value of sal_emp.se_bank_card
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeBankCard() {
        return seBankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_bank_card
     *
     * @param seBankCard the value for sal_emp.se_bank_card
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeBankCard(String seBankCard) {
        this.seBankCard = seBankCard == null ? null : seBankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_weal_address
     *
     * @return the value of sal_emp.se_weal_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeWealAddress() {
        return seWealAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_weal_address
     *
     * @param seWealAddress the value for sal_emp.se_weal_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeWealAddress(String seWealAddress) {
        this.seWealAddress = seWealAddress == null ? null : seWealAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_weal_pos
     *
     * @return the value of sal_emp.se_weal_pos
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeWealPos() {
        return seWealPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_weal_pos
     *
     * @param seWealPos the value for sal_emp.se_weal_pos
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeWealPos(String seWealPos) {
        this.seWealPos = seWealPos == null ? null : seWealPos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_isovertime
     *
     * @return the value of sal_emp.se_isovertime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeIsovertime() {
        return seIsovertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_isovertime
     *
     * @param seIsovertime the value for sal_emp.se_isovertime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeIsovertime(String seIsovertime) {
        this.seIsovertime = seIsovertime == null ? null : seIsovertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_attendance
     *
     * @return the value of sal_emp.se_attendance
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeAttendance() {
        return seAttendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_attendance
     *
     * @param seAttendance the value for sal_emp.se_attendance
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeAttendance(String seAttendance) {
        this.seAttendance = seAttendance == null ? null : seAttendance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_card_num
     *
     * @return the value of sal_emp.se_card_num
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeCardNum() {
        return seCardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_card_num
     *
     * @param seCardNum the value for sal_emp.se_card_num
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeCardNum(String seCardNum) {
        this.seCardNum = seCardNum == null ? null : seCardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_isenabled
     *
     * @return the value of sal_emp.se_isenabled
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeIsenabled() {
        return seIsenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_isenabled
     *
     * @param seIsenabled the value for sal_emp.se_isenabled
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeIsenabled(String seIsenabled) {
        this.seIsenabled = seIsenabled == null ? null : seIsenabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_inser_date
     *
     * @return the value of sal_emp.se_inser_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getSeInserDate() {
        return seInserDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_inser_date
     *
     * @param seInserDate the value for sal_emp.se_inser_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeInserDate(Date seInserDate) {
        this.seInserDate = seInserDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_code
     *
     * @return the value of sal_emp.se_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeCode() {
        return seCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_code
     *
     * @param seCode the value for sal_emp.se_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeCode(String seCode) {
        this.seCode = seCode == null ? null : seCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_alt_date
     *
     * @return the value of sal_emp.se_alt_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getSeAltDate() {
        return seAltDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_alt_date
     *
     * @param seAltDate the value for sal_emp.se_alt_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeAltDate(Date seAltDate) {
        this.seAltDate = seAltDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_inser_user
     *
     * @return the value of sal_emp.se_inser_user
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeInserUser() {
        return seInserUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_inser_user
     *
     * @param seInserUser the value for sal_emp.se_inser_user
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeInserUser(String seInserUser) {
        this.seInserUser = seInserUser == null ? null : seInserUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_alt_user
     *
     * @return the value of sal_emp.se_alt_user
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeAltUser() {
        return seAltUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_alt_user
     *
     * @param seAltUser the value for sal_emp.se_alt_user
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeAltUser(String seAltUser) {
        this.seAltUser = seAltUser == null ? null : seAltUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_end_date
     *
     * @return the value of sal_emp.se_end_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getSeEndDate() {
        return seEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_end_date
     *
     * @param seEndDate the value for sal_emp.se_end_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeEndDate(Date seEndDate) {
        this.seEndDate = seEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_user_code
     *
     * @return the value of sal_emp.se_user_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeUserCode() {
        return seUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_user_code
     *
     * @param seUserCode the value for sal_emp.se_user_code
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeUserCode(String seUserCode) {
        this.seUserCode = seUserCode == null ? null : seUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_per_tel
     *
     * @return the value of sal_emp.se_per_tel
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSePerTel() {
        return sePerTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_per_tel
     *
     * @param sePerTel the value for sal_emp.se_per_tel
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSePerTel(String sePerTel) {
        this.sePerTel = sePerTel == null ? null : sePerTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_plan_sign_date
     *
     * @return the value of sal_emp.se_plan_sign_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getSePlanSignDate() {
        return sePlanSignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_plan_sign_date
     *
     * @param sePlanSignDate the value for sal_emp.se_plan_sign_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSePlanSignDate(Date sePlanSignDate) {
        this.sePlanSignDate = sePlanSignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_sign_date
     *
     * @return the value of sal_emp.se_sign_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getSeSignDate() {
        return seSignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_sign_date
     *
     * @param seSignDate the value for sal_emp.se_sign_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeSignDate(Date seSignDate) {
        this.seSignDate = seSignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_credit_date
     *
     * @return the value of sal_emp.se_credit_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getSeCreditDate() {
        return seCreditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_credit_date
     *
     * @param seCreditDate the value for sal_emp.se_credit_date
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeCreditDate(Date seCreditDate) {
        this.seCreditDate = seCreditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_college
     *
     * @return the value of sal_emp.se_college
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeCollege() {
        return seCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_college
     *
     * @param seCollege the value for sal_emp.se_college
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeCollege(String seCollege) {
        this.seCollege = seCollege == null ? null : seCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_address
     *
     * @return the value of sal_emp.se_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeAddress() {
        return seAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_address
     *
     * @param seAddress the value for sal_emp.se_address
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeAddress(String seAddress) {
        this.seAddress = seAddress == null ? null : seAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_remark
     *
     * @return the value of sal_emp.se_remark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeRemark() {
        return seRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_remark
     *
     * @param seRemark the value for sal_emp.se_remark
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeRemark(String seRemark) {
        this.seRemark = seRemark == null ? null : seRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_pic
     *
     * @return the value of sal_emp.se_pic
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSePic() {
        return sePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_pic
     *
     * @param sePic the value for sal_emp.se_pic
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSePic(String sePic) {
        this.sePic = sePic == null ? null : sePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_log
     *
     * @return the value of sal_emp.se_log
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeLog() {
        return seLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_log
     *
     * @param seLog the value for sal_emp.se_log
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeLog(String seLog) {
        this.seLog = seLog == null ? null : seLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_edc_bac
     *
     * @return the value of sal_emp.se_edc_bac
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeEdcBac() {
        return seEdcBac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_edc_bac
     *
     * @param seEdcBac the value for sal_emp.se_edc_bac
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeEdcBac(String seEdcBac) {
        this.seEdcBac = seEdcBac == null ? null : seEdcBac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_work_ex
     *
     * @return the value of sal_emp.se_work_ex
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeWorkEx() {
        return seWorkEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_work_ex
     *
     * @param seWorkEx the value for sal_emp.se_work_ex
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeWorkEx(String seWorkEx) {
        this.seWorkEx = seWorkEx == null ? null : seWorkEx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_emp.se_transfer
     *
     * @return the value of sal_emp.se_transfer
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getSeTransfer() {
        return seTransfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_emp.se_transfer
     *
     * @param seTransfer the value for sal_emp.se_transfer
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSeTransfer(String seTransfer) {
        this.seTransfer = seTransfer == null ? null : seTransfer.trim();
    }
}