package com.money.debt.bean;

public class SysColumn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_column.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_column.field
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_column.width
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_column.sortable
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Boolean sortable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_column.title
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_column.grop_no
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String gropNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_column.order_no
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_column.align
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String align;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_column. indicate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String indicate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_column.id
     *
     * @return the value of sys_column.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_column.id
     *
     * @param id the value for sys_column.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_column.field
     *
     * @return the value of sys_column.field
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_column.field
     *
     * @param field the value for sys_column.field
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_column.width
     *
     * @return the value of sys_column.width
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_column.width
     *
     * @param width the value for sys_column.width
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_column.sortable
     *
     * @return the value of sys_column.sortable
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Boolean getSortable() {
        return sortable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_column.sortable
     *
     * @param sortable the value for sys_column.sortable
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setSortable(Boolean sortable) {
        this.sortable = sortable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_column.title
     *
     * @return the value of sys_column.title
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_column.title
     *
     * @param title the value for sys_column.title
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_column.grop_no
     *
     * @return the value of sys_column.grop_no
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getGropNo() {
        return gropNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_column.grop_no
     *
     * @param gropNo the value for sys_column.grop_no
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setGropNo(String gropNo) {
        this.gropNo = gropNo == null ? null : gropNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_column.order_no
     *
     * @return the value of sys_column.order_no
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_column.order_no
     *
     * @param orderNo the value for sys_column.order_no
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_column.align
     *
     * @return the value of sys_column.align
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getAlign() {
        return align;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_column.align
     *
     * @param align the value for sys_column.align
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setAlign(String align) {
        this.align = align == null ? null : align.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_column. indicate
     *
     * @return the value of sys_column. indicate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getIndicate() {
        return indicate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_column. indicate
     *
     * @param indicate the value for sys_column. indicate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setIndicate(String indicate) {
        this.indicate = indicate == null ? null : indicate.trim();
    }
}