package com.money.debt.bean;

import java.util.Date;

public class SysTimerTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.description
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.jobClass
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String jobclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.cronExpression
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String cronexpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.params
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.modify_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String modifyEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_timer_task.error_email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String errorEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.id
     *
     * @return the value of sys_timer_task.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.id
     *
     * @param id the value for sys_timer_task.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.name
     *
     * @return the value of sys_timer_task.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.name
     *
     * @param name the value for sys_timer_task.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.description
     *
     * @return the value of sys_timer_task.description
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.description
     *
     * @param description the value for sys_timer_task.description
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.jobClass
     *
     * @return the value of sys_timer_task.jobClass
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getJobclass() {
        return jobclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.jobClass
     *
     * @param jobclass the value for sys_timer_task.jobClass
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setJobclass(String jobclass) {
        this.jobclass = jobclass == null ? null : jobclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.cronExpression
     *
     * @return the value of sys_timer_task.cronExpression
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCronexpression() {
        return cronexpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.cronExpression
     *
     * @param cronexpression the value for sys_timer_task.cronExpression
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCronexpression(String cronexpression) {
        this.cronexpression = cronexpression == null ? null : cronexpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.params
     *
     * @return the value of sys_timer_task.params
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.params
     *
     * @param params the value for sys_timer_task.params
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.state
     *
     * @return the value of sys_timer_task.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.state
     *
     * @param state the value for sys_timer_task.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.create_time
     *
     * @return the value of sys_timer_task.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.create_time
     *
     * @param createTime the value for sys_timer_task.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.modify_time
     *
     * @return the value of sys_timer_task.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.modify_time
     *
     * @param modifyTime the value for sys_timer_task.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.create_emp_id
     *
     * @return the value of sys_timer_task.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.create_emp_id
     *
     * @param createEmpId the value for sys_timer_task.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.modify_emp_id
     *
     * @return the value of sys_timer_task.modify_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getModifyEmpId() {
        return modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.modify_emp_id
     *
     * @param modifyEmpId the value for sys_timer_task.modify_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setModifyEmpId(String modifyEmpId) {
        this.modifyEmpId = modifyEmpId == null ? null : modifyEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_timer_task.error_email
     *
     * @return the value of sys_timer_task.error_email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getErrorEmail() {
        return errorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_timer_task.error_email
     *
     * @param errorEmail the value for sys_timer_task.error_email
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setErrorEmail(String errorEmail) {
        this.errorEmail = errorEmail == null ? null : errorEmail.trim();
    }
}