package com.money.debt.bean;

public class SysUserColumnRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_column_relation.user_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_column_relation.column_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String columnId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_column_relation.user_id
     *
     * @return the value of sys_user_column_relation.user_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_column_relation.user_id
     *
     * @param userId the value for sys_user_column_relation.user_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_column_relation.column_id
     *
     * @return the value of sys_user_column_relation.column_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_column_relation.column_id
     *
     * @param columnId the value for sys_user_column_relation.column_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setColumnId(String columnId) {
        this.columnId = columnId == null ? null : columnId.trim();
    }
}