package com.money.debt.bean;

public class Table2 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table2.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table2.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table2.id
     *
     * @return the value of table2.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table2.id
     *
     * @param id the value for table2.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table2.name
     *
     * @return the value of table2.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table2.name
     *
     * @param name the value for table2.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}