package com.money.debt.bean;

import java.math.BigDecimal;
import java.util.Date;

public class TargetAchieve {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.org_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.achieve
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private BigDecimal achieve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.year
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.month
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.create_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.modify_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String modifyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_achieve.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.id
     *
     * @return the value of target_achieve.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.id
     *
     * @param id the value for target_achieve.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.state
     *
     * @return the value of target_achieve.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.state
     *
     * @param state the value for target_achieve.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.org_id
     *
     * @return the value of target_achieve.org_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.org_id
     *
     * @param orgId the value for target_achieve.org_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.emp_id
     *
     * @return the value of target_achieve.emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.emp_id
     *
     * @param empId the value for target_achieve.emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.emp_name
     *
     * @return the value of target_achieve.emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.emp_name
     *
     * @param empName the value for target_achieve.emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.achieve
     *
     * @return the value of target_achieve.achieve
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public BigDecimal getAchieve() {
        return achieve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.achieve
     *
     * @param achieve the value for target_achieve.achieve
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setAchieve(BigDecimal achieve) {
        this.achieve = achieve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.year
     *
     * @return the value of target_achieve.year
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.year
     *
     * @param year the value for target_achieve.year
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.month
     *
     * @return the value of target_achieve.month
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.month
     *
     * @param month the value for target_achieve.month
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.create_name
     *
     * @return the value of target_achieve.create_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.create_name
     *
     * @param createName the value for target_achieve.create_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.create_time
     *
     * @return the value of target_achieve.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.create_time
     *
     * @param createTime the value for target_achieve.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.modify_name
     *
     * @return the value of target_achieve.modify_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getModifyName() {
        return modifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.modify_name
     *
     * @param modifyName the value for target_achieve.modify_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setModifyName(String modifyName) {
        this.modifyName = modifyName == null ? null : modifyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_achieve.modify_time
     *
     * @return the value of target_achieve.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_achieve.modify_time
     *
     * @param modifyTime the value for target_achieve.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}