package com.money.debt.bean;

public class TBasePinyin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_pinyin.code_
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_pinyin.pin_yin_
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String pinYin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_pinyin.code_
     *
     * @return the value of t_base_pinyin.code_
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_pinyin.code_
     *
     * @param code the value for t_base_pinyin.code_
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_pinyin.pin_yin_
     *
     * @return the value of t_base_pinyin.pin_yin_
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getPinYin() {
        return pinYin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_pinyin.pin_yin_
     *
     * @param pinYin the value for t_base_pinyin.pin_yin_
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setPinYin(String pinYin) {
        this.pinYin = pinYin == null ? null : pinYin.trim();
    }
}