package com.money.debt.bean;

import java.util.Date;

public class TimeOutStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.cno
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.org_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.phoneCountTotal
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer phonecounttotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.connectCountTotal
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer connectcounttotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.bridgeDurationTotal
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String bridgedurationtotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.callOutConnectDurationAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String calloutconnectdurationavg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.callOutConnectRate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String calloutconnectrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.bridgeDurationDayAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String bridgedurationdayavg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_out_statistics.createTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.id
     *
     * @return the value of time_out_statistics.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.id
     *
     * @param id the value for time_out_statistics.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.time
     *
     * @return the value of time_out_statistics.time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.time
     *
     * @param time the value for time_out_statistics.time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.cno
     *
     * @return the value of time_out_statistics.cno
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.cno
     *
     * @param cno the value for time_out_statistics.cno
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.emp_id
     *
     * @return the value of time_out_statistics.emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.emp_id
     *
     * @param empId the value for time_out_statistics.emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEmpId(String empId) {
        this.empId = empId == null ? null : empId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.emp_name
     *
     * @return the value of time_out_statistics.emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.emp_name
     *
     * @param empName the value for time_out_statistics.emp_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.org_id
     *
     * @return the value of time_out_statistics.org_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.org_id
     *
     * @param orgId the value for time_out_statistics.org_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.phoneCountTotal
     *
     * @return the value of time_out_statistics.phoneCountTotal
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getPhonecounttotal() {
        return phonecounttotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.phoneCountTotal
     *
     * @param phonecounttotal the value for time_out_statistics.phoneCountTotal
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setPhonecounttotal(Integer phonecounttotal) {
        this.phonecounttotal = phonecounttotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.connectCountTotal
     *
     * @return the value of time_out_statistics.connectCountTotal
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getConnectcounttotal() {
        return connectcounttotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.connectCountTotal
     *
     * @param connectcounttotal the value for time_out_statistics.connectCountTotal
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setConnectcounttotal(Integer connectcounttotal) {
        this.connectcounttotal = connectcounttotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.bridgeDurationTotal
     *
     * @return the value of time_out_statistics.bridgeDurationTotal
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getBridgedurationtotal() {
        return bridgedurationtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.bridgeDurationTotal
     *
     * @param bridgedurationtotal the value for time_out_statistics.bridgeDurationTotal
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setBridgedurationtotal(String bridgedurationtotal) {
        this.bridgedurationtotal = bridgedurationtotal == null ? null : bridgedurationtotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.callOutConnectDurationAvg
     *
     * @return the value of time_out_statistics.callOutConnectDurationAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCalloutconnectdurationavg() {
        return calloutconnectdurationavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.callOutConnectDurationAvg
     *
     * @param calloutconnectdurationavg the value for time_out_statistics.callOutConnectDurationAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCalloutconnectdurationavg(String calloutconnectdurationavg) {
        this.calloutconnectdurationavg = calloutconnectdurationavg == null ? null : calloutconnectdurationavg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.callOutConnectRate
     *
     * @return the value of time_out_statistics.callOutConnectRate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCalloutconnectrate() {
        return calloutconnectrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.callOutConnectRate
     *
     * @param calloutconnectrate the value for time_out_statistics.callOutConnectRate
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCalloutconnectrate(String calloutconnectrate) {
        this.calloutconnectrate = calloutconnectrate == null ? null : calloutconnectrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.bridgeDurationDayAvg
     *
     * @return the value of time_out_statistics.bridgeDurationDayAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getBridgedurationdayavg() {
        return bridgedurationdayavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.bridgeDurationDayAvg
     *
     * @param bridgedurationdayavg the value for time_out_statistics.bridgeDurationDayAvg
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setBridgedurationdayavg(String bridgedurationdayavg) {
        this.bridgedurationdayavg = bridgedurationdayavg == null ? null : bridgedurationdayavg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_out_statistics.createTime
     *
     * @return the value of time_out_statistics.createTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_out_statistics.createTime
     *
     * @param createtime the value for time_out_statistics.createTime
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}