package com.money.debt.bean;

import java.util.Date;

public class UserLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.user_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.operate_content
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String operateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.user_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.login_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.ip_addr
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String ipAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.id
     *
     * @return the value of user_log.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.id
     *
     * @param id the value for user_log.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.type
     *
     * @return the value of user_log.type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.type
     *
     * @param type the value for user_log.type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.user_name
     *
     * @return the value of user_log.user_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.user_name
     *
     * @param userName the value for user_log.user_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.create_time
     *
     * @return the value of user_log.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.create_time
     *
     * @param createTime the value for user_log.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.operate_content
     *
     * @return the value of user_log.operate_content
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getOperateContent() {
        return operateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.operate_content
     *
     * @param operateContent the value for user_log.operate_content
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setOperateContent(String operateContent) {
        this.operateContent = operateContent == null ? null : operateContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.user_id
     *
     * @return the value of user_log.user_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.user_id
     *
     * @param userId the value for user_log.user_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.login_name
     *
     * @return the value of user_log.login_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.login_name
     *
     * @param loginName the value for user_log.login_name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.ip_addr
     *
     * @return the value of user_log.ip_addr
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.ip_addr
     *
     * @param ipAddr the value for user_log.ip_addr
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }
}