package com.money.debt.bean;

import java.util.Date;

public class VisitTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_template.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_template.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_template.type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_template.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_template.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String createEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_template.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_template.modify_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String modifyEmpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_template.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visit_template.content
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_template.id
     *
     * @return the value of visit_template.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_template.id
     *
     * @param id the value for visit_template.id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_template.name
     *
     * @return the value of visit_template.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_template.name
     *
     * @param name the value for visit_template.name
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_template.type
     *
     * @return the value of visit_template.type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_template.type
     *
     * @param type the value for visit_template.type
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_template.state
     *
     * @return the value of visit_template.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_template.state
     *
     * @param state the value for visit_template.state
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_template.create_emp_id
     *
     * @return the value of visit_template.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getCreateEmpId() {
        return createEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_template.create_emp_id
     *
     * @param createEmpId the value for visit_template.create_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateEmpId(String createEmpId) {
        this.createEmpId = createEmpId == null ? null : createEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_template.create_time
     *
     * @return the value of visit_template.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_template.create_time
     *
     * @param createTime the value for visit_template.create_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_template.modify_emp_id
     *
     * @return the value of visit_template.modify_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getModifyEmpId() {
        return modifyEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_template.modify_emp_id
     *
     * @param modifyEmpId the value for visit_template.modify_emp_id
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setModifyEmpId(String modifyEmpId) {
        this.modifyEmpId = modifyEmpId == null ? null : modifyEmpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_template.modify_time
     *
     * @return the value of visit_template.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_template.modify_time
     *
     * @param modifyTime the value for visit_template.modify_time
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visit_template.content
     *
     * @return the value of visit_template.content
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visit_template.content
     *
     * @param content the value for visit_template.content
     *
     * @mbggenerated Sat May 12 13:09:34 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}